services:
  respirador:
      container_name: ${APP_NAME:-respirador}-${ENV_NAME:-dev}
      image: ${APP_NAME:-respirador}:${ENV_NAME:-dev}
      build:
        context: ./respirador
        dockerfile: ./Dockerfile
        args:
          APP_NAME: ${APP_NAME:-respirador}
          ENV_NAME: ${ENV_NAME:-dev}
      ports:
        - "${SINAIS_VITAIS_PORT:-7003}:8000"
      volumes:
        - ./respirador:/usr/app
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT:-7003}/health || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 5